language: java
sudo: true
install: true
before_script:
  - sudo sysctl -w vm.max_map_count=262144
jdk:
  - openjdk11
script:
  - mvn clean install
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/04820972e9b664f3140c
    on_success: change
    on_failure: always
    on_start: never
